server:
  port: 8899
spring:
  application:
    name: gateway
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service1
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://discovery01:8800/eureka/