server:
  port: 8800
spring:
  application:
    name: discovery01
eureka:
  instance:
    hostname: discovery01
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://discovery02:8801/eureka/
